### ISSUE TITLE
How to prepare your .pkl file for lidc_exp?

### ISSUE THREAD

**Issue by pidanxhq** [MIC-DKFZ/medicaldetectiontoolkit#1]
Nice work. I'm reading your code. I wanna know how do you prepare your .pkl file for lidc_exp. What is your LIDC data structure .

**Comment by pfjaeger** [comment]
Sorry for the delay, I also mirrored this repository to my private account, where I am actively answering issues.  The code to convert raw downloaded LIDC data to nrrd files can be found here: https://github.com/MIC-DKFZ/LIDC-IDRI-processing

The actual preprocessing, where the .pkl file and the numpy arrays are generated is at experiments/lidc_exp/preprocessing.py
