### ISSUE TITLE
Dataloader in lidc_exp

### ISSUE THREAD

**Issue by devinxzhang** [MIC-DKFZ/medicaldetectiontoolkit#12]
What is the format of the input in lidc_exp? I followed preprocessing.py, and set my dataset folder as :

path/to/dataset/pp_norm/xxxxxx_img.npy
path/to/dataset/pp_norm/xxxxxx_rois.npy
...
...
path/to/dataset/pp_norm/info_df.pickle

However, when I run the training, the program got struck at exec.py: batch = next(batch_gen['train']).
There should be some bugs when I prepared my input.
Hope to get some help, thanks!

**Comment by octaviomtz** [comment]
Hi @DevinCheung , I have the same problem that you mention. Did you find out what was the issue or how to solve it?

**Comment by devinxzhang** [comment]
@octaviomtz I have managed to run the code. Can you make a specific description about you problem?

**Comment by wgs123** [comment]
Can you run the  preprocessing.py ? What files I need?

**Comment by pfjaeger** [comment]
see here: https://github.com/pfjaeger/medicaldetectiontoolkit/issues/2

**Comment by wgs123** [comment]
I copy the code and make the characteristics.csv,
In the preprocessing.py
df = pd.read_csv(os.path.join('C\\', 'characteristics.csv'), sep=';')
    df = df[df.PatientID == pid]
the PatientID is not in characteristics.csv

**Comment by pfjaeger** [comment]
what does your characteristics.csv look like?

**Comment by wgs123** [comment]
The first  row like  0078a;0;anonymous;00000000;-1;-1;-1;-1;-1;-1;-1;-1;-1

**Comment by pfjaeger** [comment]
0078a is the PatientID. Is there no header in your file?

**Comment by wgs123** [comment]
Yes，and I  run #2 code , but there is no header in my file

**Comment by wgs123** [comment]
And I would like to know the header

**Comment by pfjaeger** [comment]
Ok thanks for reporting, I will check back with my colleague , who wrote the data conversion.
As a quick fix for you, this is the header of characteristics.csv:

> PatientID;SessionID;Radiologist;NoduleID;Subtlety;InternalStructure;Calcification;Sphericity;Margin;Lobulation;Spiculation;Texture;Malignancy

**Comment by pfjaeger** [comment]
The data conversion tools have been updated and the header is now produced by default, apologies for the confusion

**Comment by ivanwilliammd** [comment]
> Ok thanks for reporting, I will check back with my colleague , who wrote the data conversion.
> As a quick fix for you, this is the header of characteristics.csv:
> 
> > PatientID;SessionID;Radiologist;NoduleID;Subtlety;InternalStructure;Calcification;Sphericity;Margin;Lobulation;Spiculation;Texture;Malignancy

Hi Sir Paul @pfjaeger, for the updated data conversion tools code from https://github.com/MIC-DKFZ/LIDC-IDRI-processing/tree/v1.0.1 actually generated different multiple-repeated header for non-fully downloaded LIDC dataset (in my case, I only download 10 LIDC dataset)
The header generated are :
> Patient_ID;Session_ID;Radiologist;Nodule_Str;subtlety;internalStructure;calcification;sphericity;margin;lobulation;spiculation;texture;malignancy

**Comment by renxx08** [comment]
@DevinCheung I met the same problem. When I excuted the  'python exec.py --mode train --exp_source experiments/my_experiment --exp_dir path/to/experiment/directory' . I aslo got struck at exec.py: batch = next(batch_gen['train']). The terminal show that 'starting training epoch 1'. Could you please tell me how to solve this problem?

**Comment by pfjaeger** [comment]
I assume you are stuck here: dataloader_utils/get_class_balanced_patients
Are you sure there is at least one training instance present of each class in your training data?
I will add a warning in the next commit.

**Comment by pfjaeger** [comment]
or do you have less than 2 foreground classes? if yes, then do not use this function.
