### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by wgs123** [MIC-DKFZ/medicaldetectiontoolkit#13]
Hi, I could not find  the dataset of  lung, could you tell me use  it?

**Comment by pfjaeger** [comment]
Hi, thanks for reaching out.

Please look at this closed issue for where to find the data convertion tools:

https://github.com/pfjaeger/medicaldetectiontoolkit/issues/2

**Comment by wgs123** [comment]
Thanks your help. But I also have a problem. I  have seen the label with 3d mask rcnn. So I would like to know the details. What is the difference with 2d mask rcnn?

**Comment by pfjaeger** [comment]
nD Mask R-CNN takes nD Images as Input, applies nD kernels, and produces nD box predictions. If you don’t have much experience with 3D models, maybe reading the 3D u-net paper would be a good start: 
https://arxiv.org/abs/1606.06650
