### ISSUE TITLE
cuda function crop_and_resize: different signatures for cpu and gpu versions

### ISSUE THREAD

**Issue by ThomasLecat** [MIC-DKFZ/medicaldetectiontoolkit#14]
Hi Paul,

I was trying to get the code to run on cpu only for developing and testing on my local PC before training on a machine equipped with GPU(s).

Unfortunately, there is an issue with the following lines:

https://github.com/pfjaeger/medicaldetectiontoolkit/blob/695277d581128e210893fd0be5068868f21c9dfc/cuda_functions/roi_align_3D/roi_align/crop_and_resize.py#L21-L28

When called, the cpu-only function `_backend.crop_and_resize_forward` returns an error "crop_and_resize_forward expected 7 arguments, got 8".

This function is defined in the file ._crop_and_resize.so which is a compiled library so we don't access to the code. 
Would you have access to the definition/signature of this function and be able to help resolve this issue ?

Thanks !

**Comment by pfjaeger** [comment]
hi, thanks for reaching out. 
Are you running 3D experiments? I did not implement 3D roialign for cpu. but feel free to do so.
The code is in cuda_functions/roi_align_3D/roi_align/src/crop_and_resize.c (right now just copied from 2D, which might be the cause of your error.)

afterwards compile with  `python build.py`

**Comment by ThomasLecat** [comment]
Thanks! Indeed, the C code was included already, I must be blind.
I'll look into it and make a PR if I can adapt it to 3D.

**Comment by ThomasLecat** [comment]
Hi, 

`python build.py` returns an error both for roi_align_2D and roi_align_3D:

> error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’

This issue is referenced here [https://github.com/longcw/RoIAlign.pytorch/issues/11](url) and addressed by this PR: [https://github.com/longcw/RoIAlign.pytorch/pull/13](url)

Apparently, it is caused by API changes in PyTorch between versions 0.4.0 and 0.4.1

Would you mind applying the modifications introduced by this PR here too ? I can apply these changes and create another PR if you want.

I have tested that the following things work after applying those modifications:
- `python build.py` executes without errors on both CPU only and Cuda capable machines
- The (2D) toy_experiment runs on GPU and CPU using the new `_crop_and_resize.so` file created after compiling

**Comment by ThomasLecat** [comment]
Submitted PR for this above-mentioned issue with PyTorch 0.4.1:
https://github.com/pfjaeger/medicaldetectiontoolkit/pull/16

**Comment by pfjaeger** [comment]
thanks for the PR, sorry I didn't get to it last week. I will merge it next week.
cheers!

**Comment by pfjaeger** [comment]
I merged your PR in the new commit. Sorry I could not do this directly on github, because for legal reasons this repository is mirrored from an intern phabricator repo. Anyway thanks again for your help. If you like to contribute in the future, I will try to find a way, to make your efforts visible to the public.

**Comment by Abbsalehi** [comment]
> Hi Paul,
> 
> I was trying to get the code to run on cpu only for developing and testing on my local PC before training on a machine equipped with GPU(s).
> 
> Unfortunately, there is an issue with the following lines:
> 
> https://github.com/pfjaeger/medicaldetectiontoolkit/blob/695277d581128e210893fd0be5068868f21c9dfc/cuda_functions/roi_align_3D/roi_align/crop_and_resize.py#L21-L28
> 
> When called, the cpu-only function `_backend.crop_and_resize_forward` returns an error "crop_and_resize_forward expected 7 arguments, got 8".
> 
> This function is defined in the file ._crop_and_resize.so which is a compiled library so we don't access to the code. Would you have access to the definition/signature of this function and be able to help resolve this issue ?
> 
> Thanks !

Hi @ThomasLecat thanks for sharing the problem!  I have the  same problem, could you find a way to fix it? I am trying to run this below code:
python 3.6.10
pytorch= 0.4.0

```
>>> import _crop_and_resize as _backend 
```
