### ISSUE TITLE
Training the model for custom datatset

### ISSUE THREAD

**Issue by naveennaidu** [MIC-DKFZ/medicaldetectiontoolkit#17]
Hi @pfjaeger,
Thanks for your simplified implementation of Retina U-Net in pytorch.

I have a custom 2d image dataset which has 5 classes, I would like to train a Retina U-Net model for that? Where do I get started, what changes need to be made?

Can you please upload the toy dataset? I'm going through the code but unable to follow.

**Comment by pfjaeger** [comment]
Hi,
thank you for your interest!
I am not sure what you mean by "simplified implementation", this is the original implementation of Retina U-Net and as far as I know the only one. 

The toy dataset is generated by running 
https://github.com/pfjaeger/medicaldetectiontoolkit/blob/master/experiments/toy_exp/generate_toys.py

I guess this is a good starting point to get familiar with the framework. Then you need to write your own dataloader based on the two examples provided (toys and lidc). Thats basically it.
