### ISSUE TITLE
I have problems for 4channel dataset to run mask rcnn

### ISSUE THREAD

**Issue by cammu00** [MIC-DKFZ/medicaldetectiontoolkit#18]
Hi, pfjaeger.
I'm trying to run mask rcnn with Brats dataset.
I created 4channel .npy dataset with brats(t1, t1ce, t2, flair).
When I run training, I met some error for like that
assert len(crop_size) == len(data_shape) - 2, "If you provide a list/tuple as center crop make sure it has the same dimension as your data (2d/3d)"
AssertionError: If you provide a list/tuple as center crop make sure it has the same dimension as your data (2d/3d).

before training , I modified dataloader.py for read multichannel data.
data = np.transpose(np.load(patient['data'], mmap_mode='r'), axes=(0, 1, 2, 3))[np.newaxis]
seg = np.transpose(np.load(patient['seg'], mmap_mode='r'), axes=(0, 1, 2, 3))

Could you comment for this error to resolve the problem? 
Best,
David.

**Comment by pfjaeger** [comment]
hi. What is the shape of the data array, which your 'generate_train_batch' method returns?
it should be (batch, channel, x, y, (z)). If you are using the lidc data loader as a starting point, note, that it has a dummy dimension for channels already (np.newaxis in line 232).

**Comment by cammu00** [comment]
Hi, Thank you for your response.
The shape of my data is (4, 240,240,155)
I modified the lidc data loader like following this:
 #data = np.transpose(np.load(patient['data'], mmap_mode='r'), axes=(1, 2, 0))[np.newaxis]
   data = np.transpose(np.load(patient['data'], mmap_mode='r'), axes=(0, 1, 2, 3))[np.newaxis]
and generate_train_batch returns (4, 1, 4, 156, 96, 240).

Best,
David.

**Comment by cammu00** [comment]
Thank you for your comments.
I removed dummy dimension for channels as your comments. And now training process is work!
If I meet some error, I will ask you again :)
Thank you.

Best,
David.

**Comment by cammu00** [comment]
Sorry, just in case.
If I run n_channel dataset, do I have to match data shape with seg_data(roi mask)?

best,
David.

**Comment by pfjaeger** [comment]
you need to get rid of the [np.newaxis]. This introduces a dummy channel dimension for lidc data, which you dont need. As I said, check that generate_train_batch returns (batch, channel, x, y, (z))

**Comment by pfjaeger** [comment]
the seg should have shape (batch, 1, x, y, (z)) and contain class labels as integer values.

**Comment by cammu00** [comment]
Thank you. training code now is work!
But  I met an error after first epoch following like this:
Traceback (most recent call last):
  File "exec.py", line 172, in <module>
    train(logger)
  File "exec.py", line 85, in train
    _, monitor_metrics['train'] = train_evaluator.evaluate_predictions(train_results_list, monitor_metrics['train'])
  File "/data2/project/keras/medicaldetectiontoolkit/evaluator.py", line 191, in evaluate_predictions
    return self.return_metrics(monitor_metrics)
  File "/data2/project/keras/medicaldetectiontoolkit/evaluator.py", line 298, in return_metrics
    plotting.plot_stat_curves(all_stats, out_filename)
  File "/data2/project/keras/medicaldetectiontoolkit/plotting.py", line 263, in plot_stat_curves
    plt.plot(s[c][0], s[c][1], label=s['name'] + '_' + c)
TypeError: 'float' object is not subscriptable

Do you comment for this how to resolve it?
Many thanks, 

Best,
David.

**Comment by pfjaeger** [comment]
hi by default the plot_stat_curves are switched off in configs, because in most scenarios they are less informative than the prediction histograms. Did you intentionally switch on this flag in the configs? As for your error I was not able to reproduce this. For Debugging I recommend to print our your all_stats list and check if it has the expected structure.

**Comment by cammu00** [comment]
Hi, Thank you. I didn't realize that I did switch on it in configs. I did back to off and now it's working well.
Thank you for your help :).

Best,
David.

**Comment by pfjaeger** [comment]
glad I could help. Feel free to join our new slack channel for further discussion: https://join.slack.com/t/mdtoolkit/shared_invite/enQtNTQ3MjY2MzE0MDg2LWNjY2I2Njc5MTY0NmM0ZWIxNmQwZDRhYzk2MDdhM2QxYjliYTcwYzhkNTAxYmRkMDA0MjcyNDMyYjllNTZhY2M
