### ISSUE TITLE
Using the LIDC dataset

### ISSUE THREAD

**Issue by Riksi** [MIC-DKFZ/medicaldetectiontoolkit#2]
It looks like you have done some additional preprocessing on the LIDC dataset prior to running preprocessing.py, such as saving the data to a different format from the original DICOM files and making a csv file, characteristics.csv, with metadata in the xml files. Would you be able to share the code used on the raw data as downloaded from the source (https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI)? Thanks.

**Comment by pfjaeger** [comment]
thanks for reaching out. The preprocessing was done by a colleague who is not part of the project. I will ask him whether we can share the code and get back to you asap.

**Comment by Riksi** [comment]
Hi, any updates on this? Thanks.

**Comment by Riksi** [comment]
The following newly available dataset might be useful to anyone interested in this issue. It consists of annotations for nodules >= 3mm in DICOM format.

https://wiki.cancerimagingarchive.net/display/DOI/Standardized+representation+of+the+TCIA+LIDC-IDRI+annotations+using+DICOM

The [pylidc](https://pylidc.github.io) library is also really helpful for preprocessing.

**Comment by pfjaeger** [comment]
Good news: thanks to my colleague Michel Goetz the data convention tools are now available at https://github.com/MIC-DKFZ/LIDC-IDRI-processing/tree/v1.0.1 Sorry for the wait guys!

**Comment by shanpriya3** [comment]
#22 I am trying to preprocess the LIDC dataset but I am getting the following errors. Can anyone help me with this? 

No DICOM's found for file: /LIDC-IDRI-Preprocessing/LIDC_Dataset/XML_Data/LIDC-XML-only/tcia-lidc-xml/186/075.xml
/LIDC-IDRI-Preprocessing/LIDC_Dataset/XML_Data/LIDC-XML-only/tcia-lidc-xml/186/049.xml
/LIDC-IDRI-Preprocessing/LIDC_Dataset/XML_Data/LIDC-XML-only/tcia-lidc-xml/186/049.xml
1.3.6.1.4.1.14519.5.2.1.6279.6001.212697393127299815450339637649 1.3.6.1.4.1.14519.5.2.1.6279.6001.410251741986998833890312367579
[]
No DICOM's found for file: /LIDC-IDRI-Preprocessing/LIDC_Dataset/XML_Data/LIDC-XML-only/tcia-lidc-xml/186/049.xml
(CMAKE_QT) dv00:/LIDC-IDRI-Preprocessing/LIDC-IDRI-processing$
