### ISSUE TITLE
How to setup/convert a custom 3D dataset?

### ISSUE THREAD

**Issue by tamasbalassa** [MIC-DKFZ/medicaldetectiontoolkit#20]
Hello!

I was wondering how well could the 3D Mask-RCNN approach work on my 3D dataset (nifti). So far I was not able to find any guide or explanations of how could I apply it on a dataset that is not LIDC. Could You please explain/guide me how to convert my nifti data to have the appropriate input for the 3D Mask-RCNN?

Thank You!

**Comment by pfjaeger** [comment]
hi, thanks for reaching out.
Did you see the corresponding section in the readme of this repo?
So you need to customize the data input side to your needs. You can do this based on preprocessing.py and data_loader.py in the LIDC experiment. So preprocessing converts your niftis into numpy arrays. And the dataloader during training loads the numpy arrays and generates batches.
Let me know if you have specific questions on the way.

**Comment by tamasbalassa** [comment]
Yeah, I've seen it. I was just wondering (more like - I gave it a shot) if You are planning (or already got) some other examples for different type of data. For example: not patient based or where the required data is only raw + segmentation. 
I'll do it my way then, thanks anyway!

**Comment by leihouyeung** [comment]
@tamasbalassa How did you solve this problem? I think we have exactly the same issue. Thanks!

**Comment by tamasbalassa** [comment]
@leihouyeung I was not able to solve this problem based on the guide (mentioned above) and the help I received here. So I just gave up using this repo. Cheers!
