### ISSUE TITLE
list index out of range while testing.

### ISSUE THREAD

**Issue by cammu00** [MIC-DKFZ/medicaldetectiontoolkit#21]
Hi, 
I met an error like following while testing after training with 4ch dataset.
I think I need to change something in testing code, but I don't know exactly. I guess it's due to mismatch between 4ch data dimension and patch size dimension. could you comment for this?
my 4ch dataset dim is (4, 240,240,155). 
Logging to ./brats_tc/fold_0/exec.log
starting testing model of fold 0 in exp ./brats_tc
feature map shapes: [[32 32 64]
 [16 16 32]
 [ 8  8 16]
 [ 4  4  8]]
anchor scales: {'z': [[2], [4], [8], [16]], 'xy': [[8], [16], [32], [64]]}
level 0: built anchors (196608, 6) / expected anchors 196608 ||| total build (196608, 6) / total expected 224640
level 1: built anchors (24576, 6) / expected anchors 24576 ||| total build (221184, 6) / total expected 224640
level 2: built anchors (3072, 6) / expected anchors 3072 ||| total build (224256, 6) / total expected 224640
level 3: built anchors (384, 6) / expected anchors 384 ||| total build (224640, 6) / total expected 224640
using default pytorch weight init
subset: selected 57 instances from df
data set loaded with: 57 test patients
tmp ensembling over rank_ix:0 epoch:./brats_tc/fold_0/114_best_params.pth
Traceback (most recent call last):
  File "exec.py", line 190, in <module>
    test(logger)
  File "exec.py", line 126, in test
    test_results_list = test_predictor.predict_test_set(batch_gen, return_results=True)
  File "/data2/project/keras/medicaldetectiontoolkit/predictor.py", line 149, in predict_test_set
    batch = next(batch_gen['test'])
  File "/data2/project/keras/batchgenerators/batchgenerators/dataloading/data_loader.py", line 123, in __next__
    return self.generate_train_batch()
  File "experiments/brats_tc/data_loader.py", line 381, in generate_train_batch
    patch_crop_coords_list = dutils.get_patch_crop_coords(data, self.patch_size)
  File "/data2/project/keras/medicaldetectiontoolkit/utils/dataloader_utils.py", line 157, in get_patch_crop_coords
    n_patches = int(np.ceil(img.shape[dim] / patch_size[dim]))
IndexError: list index out of range

Thank you,
David.

**Comment by pfjaeger** [comment]
hi thanks for reaching out. can you post your configs please?

**Comment by cammu00** [comment]
Thanks for response. I used brat18 dataset with T1, T1ce, flair, and T2 . In preprocessing, I created 4ch data with this 4 files. So, 4ch dataset was combined with this 4 data file. Tumor segment file was used for ROIs. I applied mask rcnn for data training. Training stage was completed well.
I attached config.py files which was used for this.
[config.txt](https://github.com/pfjaeger/medicaldetectiontoolkit/files/2919944/config.txt)
 Best,
David.

**Comment by pfjaeger** [comment]
hey yes so like you assumed, the problem lies withing your channel dimension. As LIDC has only one channel, the LIDC data_loader does is not written for data with a multiple channels. So the image you pass to get_patch_crop_coords has 4 dimensions instead of the expected 3.  The fixes you need to make should be easy to implement, just check to shift the dimensions by one where needed in the PatientBatchIterator class.

**Comment by pfjaeger** [comment]
I will write this class more generic to avoid the problem in the future, but it might take a couple of days till I find the time. Good Luck!

**Comment by cammu00** [comment]
Thank you for your comments. I'll try it for this. I have a wondering. If I do test with shifting the dimensions by one from 4ch data, is there any difference with each separately trained data?(e.g. when I do train each dataset(T1, T1ce, T2, Flair) as 1ch dataset)

Thank you for your help.
David.

**Comment by pfjaeger** [comment]
Generally you would want to train multi-modal models so as to grasp the correlations between modalities in your model paramters. In other words, if you train separately your model will not learn relational semantics between modalities.
