### ISSUE TITLE
No DICOMS's found for file: Using LIDC dataset and LIDC-IDRI-processing tool

### ISSUE THREAD

**Issue by shanpriya3** [MIC-DKFZ/medicaldetectiontoolkit#24]
I am trying to preprocess the LIDC dataset but I am getting the following errors. Can anyone help me with this?

No DICOM's found for file: /LIDC-IDRI-Preprocessing/LIDC_Dataset/XML_Data/LIDC-XML-only/tcia-lidc-xml/186/075.xml
/LIDC-IDRI-Preprocessing/LIDC_Dataset/XML_Data/LIDC-XML-only/tcia-lidc-xml/186/049.xml
/LIDC-IDRI-Preprocessing/LIDC_Dataset/XML_Data/LIDC-XML-only/tcia-lidc-xml/186/049.xml
1.3.6.1.4.1.14519.5.2.1.6279.6001.212697393127299815450339637649 1.3.6.1.4.1.14519.5.2.1.6279.6001.410251741986998833890312367579
[]
No DICOM's found for file: /LIDC-IDRI-Preprocessing/LIDC_Dataset/XML_Data/LIDC-XML-only/tcia-lidc-xml/186/049.xml
(CMAKE_QT) dv00:/LIDC-IDRI-Preprocessing/LIDC-IDRI-processing$

**Comment by pfjaeger** [comment]
Hi,

which script are you running exactly?

**Comment by shanpriya3** [comment]
Hi I am running lidc_data_to_nifti.py 
from https://github.com/MIC-DKFZ/LIDC-IDRI-processing/tree/v1.0.1

**Comment by pfjaeger** [comment]
sorry you would need to wait for response by the owner of that repository.  Please let me know if you have not heard back from him by Wednesday next week.

**Comment by shanpriya3** [comment]
Okay, Thanks!

**Comment by shanpriya3** [comment]
Hi, I didn't receive any response yet. Could you please help?
