### ISSUE TITLE
Toy dataset generation: writing to file isn't thread safe 

### ISSUE THREAD

**Issue by ThomasLecat** [MIC-DKFZ/medicaldetectiontoolkit#3]
Hi !

First, thanks this great work. This implementation of the object detectors is very clean, well organised and one of the best I've seen so far.

I think there is an issue with the way processes write content in a dataframe when generating toy dataset: After generating and writing 1500 images to disk, the associated info_df.pickle dataframe only contains ~950 samples. 

I believe the misbehaviour comes from:

https://github.com/pfjaeger/medicaldetectiontoolkit/blob/695277d581128e210893fd0be5068868f21c9dfc/experiments/toy_exp/generate_toys.py#L53-L55

If two processes read the pickle file simultaneously, the dataframes will have the same length for both. Then, both process will write a row with the same index: `df.loc[len(df)] = ...`. Ultimately, one of the two rows is lost when the second process writes its dataframe back to disk.

**Comment by pfjaeger** [comment]
Hi thanks for your kind feedback and for pointing this out. You are completely right, we should change this. Unfortunately I am out of office until January, so for now I recommend to set the number of processes to 1.

**Comment by Riksi** [comment]
A simple fix which I am using right now would be to save a separate file for each image and merge them at the end into a single dataframe when all the images have been processed.

**Comment by pfjaeger** [comment]
fixed in new commit.
