### ISSUE TITLE
Preparaing the dataset

### ISSUE THREAD

**Issue by hi-karan-here** [MIC-DKFZ/medicaldetectiontoolkit#33]
Hello,

I went through your docs, the work seems to be very helpful and I wish to try it out. Also, I would like to ask that is it necessary  to use the script written by your friend to convert data into necessary formats. 
What if I already have LIDC-IDRI dataset segmented. Can I not use it?

Please shed some light on the pre-processing work.

**Comment by pfjaeger** [comment]
hi if you want to use the preprocessing as is, you need to convert it with the described tool. otherwise you need to adapt the code to your needs.
