### ISSUE TITLE
visualize problem

### ISSUE THREAD

**Issue by wgs123** [MIC-DKFZ/medicaldetectiontoolkit#36]
I have found the result when I choose args.mode == 'analysis': I would like to visualize the result, so how I can make it?

**Comment by pfjaeger** [comment]
please be more specific about problems. I can not help you like this.

**Comment by wgs123** [comment]
I would like to plot the prediction image like the output_monitoring_2.png in your assets file

**Comment by pfjaeger** [comment]
so this i currently not implemented. note that analysis is a light weight mode where only predictions are loaded and aggregated (not images). I do have a script that outputs aggregated predictions into a .csv file, later loads images and plots predictions on them. Will include it in the next commit. Thanks!

**Comment by wgs123** [comment]
Thanks your reply, what the date of the next commit?
