### ISSUE TITLE
How to multi-gpu parallel training?

### ISSUE THREAD

**Issue by andys0975** [MIC-DKFZ/medicaldetectiontoolkit#4]
The net use custom training method, so DataParallel can't not work for multi gpu training
The default model use only one gpu when training, even though CUDA VISIBLE is multi-gpu

**Comment by devinxzhang** [comment]
@andys0975 hi, have you solved "multi-gpu parallel training" problem? thx.

**Comment by pfjaeger** [comment]
this should be a one-liner:

https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html#create-model-and-dataparallel

**Comment by cristinaperez9** [comment]
Has anyone been able to solve this issue?
I would be really grateful if you could share :)
