### ISSUE TITLE
Calculation of box centers for wbc

### ISSUE THREAD

**Issue by oetzus** [MIC-DKFZ/medicaldetectiontoolkit#46]
Hi,
i think i found an error in the calculation of the patch center factor.
When calculating box_centers, you subtract the coordinates and then divide by 2 instead of adding them and dividing by 2. So it's not the center anymore, but the height and width (divided by 2), wherefore it's more like a weighting based on the size of the box.

https://github.com/pfjaeger/medicaldetectiontoolkit/blob/2b343ba974a6936d10bc7ba2d571db28f0760df5/predictor.py#L424

**Comment by pfjaeger** [comment]
thank you so much for catching this, I fixed it in today's commit!
