### ISSUE TITLE
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed

### ISSUE THREAD

**Issue by Cohen2902** [MIC-DKFZ/medicaldetectiontoolkit#49]
![Capture](https://user-images.githubusercontent.com/51396388/58934409-13854280-8773-11e9-96e6-58b483be8ced.PNG)
Hi,
I'm new to deep learning, can anyone please guide me what I'm doing wrong?

**Comment by pfjaeger** [comment]
Ah sorry, so the error here is Value Error low >= high. Please go to the corresponding line in the data_loader and check what causes the error. This could be associated with your data shape. E.g. specifying patch sizes in the configs that are larger than pre_crop_sizes.
