### ISSUE TITLE
Why I got square like segmentation predictions even though training with non-square binary map?

### ISSUE THREAD

**Issue by andys0975** [MIC-DKFZ/medicaldetectiontoolkit#5]
Above row shows non-square segmentation map ground truth
Why I got square like segmentation predictions such as below row?
![image](https://user-images.githubusercontent.com/21152737/49907616-e33ea480-feb1-11e8-9dcd-09b0eab54f0c.png)

**Comment by pfjaeger** [comment]
sorry i can not help you like that. I have seen square-like segmentation predictions  in the first training epochs of mask rcnn, but you would need to provide more information in order to receive useful feedback.
