### ISSUE TITLE
Showing Pred+GT at lowest row of pred_example.png

### ISSUE THREAD

**Issue by ivanwilliammd** [MIC-DKFZ/medicaldetectiontoolkit#50]
Hello Sir Paul, thank you for your awesome commit that resolve all previous issues. 
May I ask, based on readme.md and the paper, it was shown that the wcs prediction will be plotted on the lowest row of the pred_example.png, however in my case (before and after recent commit), prediction box (blue box) weren't plotted. Are there another codes needed to be added  to plotting.py in order to enable pred/gt boxes on the lowest image row?
Thanks in advance

**Comment by ivanwilliammd** [comment]
Sample of image generated using LIDC Datasets
![pred_example_0](https://user-images.githubusercontent.com/48039956/59156906-15316c00-8acd-11e9-8485-300de7c1e6c3.png)

**Comment by pfjaeger** [comment]
Hi
You need to comment line 126 in plotting.py 
I will correct this in the next commit.

**Comment by ivanwilliammd** [comment]
> Hi
> You need to comment line 126 in plotting.py
> I will correct this in the next commit.

Thanks a lot Sir. 
I will try it soon.
