### ISSUE TITLE
How should `class_id` in `generate_toys.py` be created with my own data?

### ISSUE THREAD

**Issue by Florence-Janie** [MIC-DKFZ/medicaldetectiontoolkit#57]
Sorry to ask you this question.
I try to run `Toy-Experiments` with my own data, will the `class_id` be created randomly as `generate_toys.py` do? If not, how it should be created?

**Comment by kiranintellify** [comment]
where is the answer of previous question

**Comment by pfjaeger** [comment]
Not sure if I understand  this question. The class_id is never created randomly, but represents a fundamental property of your data set. In the toy experiments it is assigned according to the different classes of generated shapes (see https://arxiv.org/abs/1811.08661). But the more general case for custom data sets would be that you have some sort of meta info dictionary or dataframe from where the class_id info is loaded (see lidc data loader line 151). In your dataloader, the class_id should be assigned as an integer [0, ..., n_classes - 1]. This variable will be automatically shifted by +1 during data augmentation to make space for the background class at value 0.
