### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by theVmagnificient** [MIC-DKFZ/medicaldetectiontoolkit#61]
Greetings! Thanks for the great work you've done on this framework. I was wondering whether I could log all the metrics while training to tensorboard. For this thing should I just change functions. `detection_monitoring_plot` and `plot_stat_curves`, so they would output to TB or things are more complex? Thanks in advance.

**Comment by pfjaeger** [comment]
hi, good idea. I am actually planning to change all plots to tensorboard in the framework as well, but will probably not have time to do that in the near future. So you basically can use tensorboardX and just do "add_figure" to port the matplotlib figures to tensorboard. Although the loss/ap monitoring curves you probably want to add them individually as scalars to get all the tb features.

**Comment by theVmagnificient** [comment]
ok, thanks for the reply!
