### ISSUE TITLE
There is a grammar error in mrcnn.py

### ISSUE THREAD

**Issue by WENJIANHUANG** [MIC-DKFZ/medicaldetectiontoolkit#63]
1.         if len(self.cf.patch_size) == 3:
2.             d = self.cf.**pach_size**[2]
3.             if d / 2**3 != int(d / 2**3):
4.                 raise Exception("Image z dimension must be dividable by 2 at least 3 times "
5. "to avoid fractions when downscaling and upscaling."

it should be "patch_size" and ")" is missing, right? 

1.         if len(self.cf.patch_size) == 3:
2.             d = self.cf.patch_size[2]
3.             if d / 2**3 != int(d / 2**3):
4.                 raise Exception("Image z dimension must be dividable by 2 at least 3 times "
5. "to avoid fractions when downscaling and upscaling.")

**Comment by pfjaeger** [comment]
many thanks! will fix this in the next commit.
