### ISSUE TITLE
the function predictor.load_saved_predictions has an unexpected input argument.

### ISSUE THREAD

**Issue by WENJIANHUANG** [MIC-DKFZ/medicaldetectiontoolkit#66]
in the execu.py funciton, the predictor.load_saved_predictions has an unexpected input argument save_preds_to_csv.

            if folds is None:
                folds = range(cf.n_cv_splits)
            for fold in folds:
                cf.fold_dir = os.path.join(cf.exp_dir, 'fold_{}'.format(fold))
                cf.fold = fold
                predictor = Predictor(cf, net=None, logger=logger, mode='analysis') 
                results_list = predictor.load_saved_predictions(apply_wbc=True, save_preds_to_csv=cf.save_preds_to_csv)
                logger.info('starting evaluation...')
                evaluator = Evaluator(cf, logger, mode='test')
                evaluator.evaluate_predictions(results_list)
                evaluator.score_test_df()

**Comment by pfjaeger** [comment]
thanks, I will fix this!
