### ISSUE TITLE
Found an error in the data_loader.py for lidc dataset

### ISSUE THREAD

**Issue by WENJIANHUANG** [MIC-DKFZ/medicaldetectiontoolkit#68]
Through testing the project, I found the following code in data_loader.py for lidc dataset probably is wrong since it produces the misshapeded data. 

new_img_batch.append(data[c[0]:c[1], c[2]:c[3], c[4]:tmp_c_5])

I changed it into 

new_img_batch.append(data[:, c[0]:c[1], c[2]:c[3], c[4]:tmp_c_5])

hope it might help.

**Comment by pfjaeger** [comment]
Thanks, I will fix this!
