### ISSUE TITLE
Interpolate in backbone.py

### ISSUE THREAD

**Issue by YoshuaDavy** [MIC-DKFZ/medicaldetectiontoolkit#69]
Hi, I want to point out an error:
In the backbone.py following lines

if conv.dim == 2:
            self.P1_upsample = Interpolate(scale_factor=2, mode='bilinear')
            self.P2_upsample = Interpolate(scale_factor=2, mode='bilinear')
        else:
            self.P1_upsample = Interpolate(scale_factor=(2, 2, 1), mode='trilinear')
            self.P2_upsample = Interpolate(scale_factor=(2, 2, 1), mode='trilinear')

You didn't mention where is the Interpolate from, so maybe you could write it more specifically.

Thank you

**Comment by pfjaeger** [comment]
See my comment on your conv class post...
