### ISSUE TITLE
the format of stride in conv3d is (D*H*W) Not (H*W*D), no 'Norm' or 'Relu' in conv3d

### ISSUE THREAD

**Issue by YoshuaDavy** [MIC-DKFZ/medicaldetectiontoolkit#70]
Another problem is that the usage of conv3d in the backbone.py is quite different from the torch website:
for example in the following code:

>  _if operate_stride1:
>             self.C0 = nn.Sequential(conv(cf.n_channels, start_filts, ks=3, pad=1, norm=cf.norm, relu=cf.relu),
>                                     conv(start_filts, start_filts, ks=3, pad=1, norm=cf.norm, relu=cf.relu))
> 
>             self.C1 = conv(start_filts, start_filts, ks=7, stride=(2, 2, 1) if conv.dim == 3 else 2, pad=3, norm=cf.norm, relu=cf.relu)
> 
>         else:
>             self.C1 = conv(cf.n_channels, start_filts, ks=7, stride=(2, 2, 1) if conv.dim == 3 else 2, pad=3, norm=cf.norm, relu=cf.relu)_

But actually, in the torch tutorial website[website](https://pytorch.org/docs/stable/nn.html#conv3d), there is no parameter called relu or norm.
Also the sequence of image size is (D*H*W) not (H*W*D), which I believe also cause the error in the stride=(2,2,1)

**Comment by pfjaeger** [comment]
the conv method belong to the NDConvGenerator class from model_utils and is a wrapper around the pytorch conv layer which handles 2D vs 3D automatically. 

I have to kinldy ask you to do some digging in the code if you do not understand something before you post here and call out an "error" or a "problem" (this comment also refers to your post about interpolation).

**Comment by YoshuaDavy** [comment]
I am sorry. I didn't see you import mutils in the backbone.py, so I don't know where is "conv" from. I apologize for missing the definition of conv. 

Your code is very good and considers many situations. But this also makes it not easy to understand. No offence, it's my just own opinion.
