### ISSUE TITLE
pred_example_{}.png  what do the additional colours mean? 

### ISSUE THREAD

**Issue by sophie-isobel** [MIC-DKFZ/medicaldetectiontoolkit#77]
Hi @pfjaeger , thank you for sharing this great repository! My pred_example_{}.png (for Mask R-CNN) is returning additional coloured boxes that are purple and white, see below:

![image](https://user-images.githubusercontent.com/31969100/64807412-0905f080-d58d-11e9-9c2c-b9939b2ff8a8.png)

I cannot find the purple and white boxes in the key in the read.me file, may i ask what they mean or why they may be appearing?
![image](https://user-images.githubusercontent.com/31969100/64807792-e0322b00-d58d-11e9-99d8-bc7168cb4079.png)

I am using the brats dataset (with 4 modalities shown above), with only one foreground class, and I am training Mask R-CNN with a subset of 20 images until i get the model working correctly. I am training 3 epochs and on the 2nd epoch of the 2nd fold the model is getting stuck, would you have any advice on why this might be happening?

UPDATE: I am now training on a server and it is no longer getting stuck, but there is still an issue with the extra boxes in the pred_example images for Mask R-CNN, see below, notice that it is also not plotting the prediction box in the bottom row. Please let me know what could be causing this, thank you in advance! 

![image](https://user-images.githubusercontent.com/31969100/64908349-c2cca080-d6f6-11e9-89e8-17b4c2e11f7c.png)

zoomed in to the issue:

![image](https://user-images.githubusercontent.com/31969100/64908360-1808b200-d6f7-11e9-9e65-ca9ebff63cc2.png)

thank you,
Sophie

**Comment by CodingHHW** [comment]
in medicaldetectiontoolkit/default_configs.py, line 96-98,
##### color specifications for all box_types in prediction_plot.
        self.box_color_palette = {'det': 'b', 'gt': 'r', 'neg_class': 'purple',
                                  'prop': 'w', 'pos_class': 'g', 'pos_anchor': 'c', 'neg_anchor': 'c'}
means
blue------>detection box
red------->ground trues
purple---->neg_class
white----->proposal box from RPN
green----->pos_class
cyan------>anchor

**Comment by Gregor1337** [comment]
Thank you, @CodingHHW, for answering this!
