### ISSUE TITLE
please explain the which type of data  provides  to  this  model

### ISSUE THREAD

**Issue by adeebakausar** [MIC-DKFZ/medicaldetectiontoolkit#81]
I would like to inquire about * * self.root dir * * = * * ' /path / to / data ' * *. This  * * data folder * * either  includes  images  and annotations? ,and please explain the format of annotation as well

https://github.com/pfjaeger/medicaldetectiontoolkit/blob/master/experiments/toy_exp/configs.py

**Comment by pfjaeger** [comment]
please run the generation script for the toy data set. it will create a folder structure which should be explicatory.
