### ISSUE TITLE
Retina U-Net does not work in the toy experiment

### ISSUE THREAD

**Issue by skief** [MIC-DKFZ/medicaldetectiontoolkit#87]
When I try to use the Retina U-Net in the toy experiment(just changed self.model = 'retina_unet' and the path to the data) the program crashes in line 447 of the retina_unet.py due to the `var_seg[:, 0]` containing the values `[0, 1, 2]` while the size of the `seg_logits` is just `[20, 2, 320, 320]` and not `[20, 3, 320, 320]`

**Comment by Gregor1337** [comment]
Hi skief,
thanks for your input.
Fixed in [this commit](https://github.com/MIC-DKFZ/medicaldetectiontoolkit/commit/3ef7d8974aa0de274fe5dcbbc23975ad30e5da01).
