### ISSUE TITLE
Issue while testing

### ISSUE THREAD

**Issue by paul-bd** [MIC-DKFZ/medicaldetectiontoolkit#9]
Hi, 

First thanks for this outstanding work! I managed to train the retina_Unet model on my patients, using the data loader from the toynet example were inputs are also 3D npy array with shape 128,128,256. I trained patients both using holding test set ==True and False and both results seem promising as shown with the plotting examples. 

Nevertheless I can't manage to make the prediction on the testing cohort as this error appear, and I don't know where it may come from. 
`(MDK) paulbd@host:~/medicaldetectiontoolkit$ python exec.py --mode test --exp_dir results/test_AUJ3
/home/paulbd/anaconda3/envs/MDK/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Logging to results/test_AUJ3/fold_0/exec.log
starting testing model of fold 0 in exp results/test_AUJ3
feature map shapes: [[32 32 64]
 [16 16 32]
 [ 8  8 16]
 [ 4  4  8]]
anchor scales: {'xy': [[8], [16], [32], [64]], 'z': [[2], [4], [8], [16]]}
level 0: built anchors (196608, 6) / expected anchors 196608 ||| total build (196608, 6) / total expected 224640
level 1: built anchors (24576, 6) / expected anchors 24576 ||| total build (221184, 6) / total expected 224640
level 2: built anchors (3072, 6) / expected anchors 3072 ||| total build (224256, 6) / total expected 224640
level 3: built anchors (384, 6) / expected anchors 384 ||| total build (224640, 6) / total expected 224640
using default pytorch weight init
data set loaded with: 97 test patients from /home/paulbd/medicaldetectiontoolkit/GAINED_dataset/test
tmp ensembling over rank_ix:0 epoch:results/test_AUJ3/fold_0/2_best_params.pth
check patient data loader (1, 1, 128, 128, 256) (1, 1, 128, 128, 256)
evaluating patient 0 for fold 0 
forwarding (patched) patient with shape: (1, 1, 128, 128, 256)
Traceback (most recent call last):
  File "exec.py", line 185, in <module>
    test(logger)
  File "exec.py", line 121, in test
    test_results_list = test_predictor.predict_test_set(batch_gen, return_results=True)
  File "/home/paulbd/medicaldetectiontoolkit/predictor.py", line 159, in predict_test_set
    results_dict = self.predict_patient(batch)
  File "/home/paulbd/medicaldetectiontoolkit/predictor.py", line 102, in predict_patient
    results_dict = self.data_aug_forward(batch)
  File "/home/paulbd/medicaldetectiontoolkit/predictor.py", line 292, in data_aug_forward
    results_list = [self.spatial_tiling_forward(batch, patch_crops)]
  File "/home/paulbd/medicaldetectiontoolkit/predictor.py", line 448, in spatial_tiling_forward
    results_dict = self.batch_tiling_forward(batch)
  File "/home/paulbd/medicaldetectiontoolkit/predictor.py", line 483, in batch_tiling_forward
    results_dict = self.net.test_forward(batch, return_masks=self.cf.return_masks_in_test)
  File "/home/paulbd/medicaldetectiontoolkit/models/tmp_model.py", line 975, in test_forward
    _, _, _, detections, detection_masks = self.forward(img)
  File "/home/paulbd/medicaldetectiontoolkit/models/tmp_model.py", line 1008, in forward
    batch_rpn_rois, batch_proposal_boxes = proposal_layer(rpn_pred_probs, rpn_pred_deltas, proposal_count, self.anchors, self.cf)
  File "/home/paulbd/medicaldetectiontoolkit/models/tmp_model.py", line 333, in proposal_layer
    anchors = anchors[order, :]
RuntimeError: index 898557 is out of bounds for dimension 0 with size 224640`

Thanks for your help and again congratulations. 

Best regards

Paul

**Comment by pfjaeger** [comment]
Hi, thanks for reaching out. It seems like you did not generate enough anchors for all predicted positions. Can you post your config file please?
One common mistake is to change the “backbone_strides” in the mrcnn configs.

**Comment by paul-bd** [comment]
Hi!

thanks for your fast return, 
I used the default config file from the LIDC experiment [configs.txt](https://github.com/pfjaeger/medicaldetectiontoolkit/files/2703171/configs.txt) and I used the loader from the toynet experiments. 

May be it is because my image are smaller ? 

Best 

Paul

**Comment by pfjaeger** [comment]
ah ok. You need to write your own data loader for this experiment based on the one from LIDC. The problem is that the toy dataloader does not handle cropping/patching, but your config file wants a patch size smaller than your image size. What happens is that during training your images are center cropped to the patch size by the data augmentation pipeline, but at test time the uncropped images are fed to the network producing your error.

**Comment by paul-bd** [comment]
ok thanks, i ll try that and share with you a 3D toynet experiment, 
best
Paul

**Comment by pfjaeger** [comment]
Actually for your purpose it might be much easier to just use 3D images of smaller size (like the patch siZe in Lidc) so you don’t need any patching.

**Comment by paul-bd** [comment]
ok so I ll start by just creating random patches of 128x128x64 from my images. 
Thanks,
